# [[container.copy.files]]
# sourceFile="./resources/products.json"
# target="/home/ballerina/products.json"
[container.image]
name="catalog-service"
repository="wso2inc"
tag="v0.1.0"

[[container.copy.files]]
sourceFile="./resources/products.json"
target="/home/ballerina/resources/products.json"

[cloud.deployment]
internal_domain_name="catalog-service"