catalogHost="prodcat-2479457892" 
cartHost="cart2-833837164" 
currencyHost="currency-2512741866" 
shippingHost="shipping-1527744195" 
paymentHost="payment-2724923889" 
emailHost="email-2406290084"
cartTimeout=3.0
catalogTimeout=3.0
currencyTimeout=3.0
shippingTimeout=3.0
paymentTimeout=3.0
emailTimeout=3.0

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="jaeger"
agentPort=55680
samplerType="const"
samplerParam=1.0
reporterFlushInterval=2000
reporterBufferSize=1000
